#
# Changes to this file will be overwritten by `trmnlp pull`.
#
# Docs: https://help.usetrmnl.com/en/articles/10542599-importing-and-exporting-private-plugins#h_581fb988f0
#
---
strategy: webhook
no_screen_padding: "no"
dark_mode: "no"
static_data: ""
polling_verb: get
polling_url: ""
polling_headers: ""
name: Postmark Incoming Feed
refresh_interval: 1440
